### ISSUE TITLE
css injection

### ISSUE THREAD

**Issue by equinusocio** [superjose/polymer-sass#2]
Why you don't inject css directly inside the template file?

**Comment by superjose** [comment]
Hi equinusocio! The reason is because you may potentially be editing the template file, and there are editors which can conflict if the file is open (As well as gulp). 

The best would be to inject it into the file once it's ready for production, and it is not needed in more than one place. 

I can definitely make the addition if you want it :)

**Comment by equinusocio** [comment]
Maybe you can just write about that in the readme 🙂

**Comment by superjose** [comment]
@equinusocio I just checked! There is no need to modify the code. It works with any file! I'll be updating the README asap. Give me a couple of minutes will be working on it.

**Comment by superjose** [comment]
@equinusocio I've been thinking for a while, I need some feedback... 

Will it be wise to include a "flag feature", in which for example I type: "gulp injectSass --main" this will inject the .scss to the main file instead of the -styles.html file?

**Comment by equinusocio** [comment]
I think `--template` is more explicit, don't you think that should be the default flag?  I have another question, how you can handle css autoprefix with this gulp code? It should be use postcss `autoprefixer` module by default.

**Comment by superjose** [comment]
Crap. Sorry for not replying sooner, didn't receive a notification by email. 

Well, I could definitely make it. Thanks for the naming, it makes more sense that way. In regards of making it default, I was against putting it in the main file because I had problems with some text editors and IDEs that were having file lock issues, and gulp wasn't able to open the file for writing.

Now that you mention postcss, I've been thinking that maybe we should make this more modular instead of a script by itself. This way people could extend it with ease. I know that Google already separated its bundling process in different gulp scripts. Maybe we could do the same. 

Thing is I have no idea on how can we make it modular by using it pipe (Logically-wise).

**Comment by equinusocio** [comment]
@superjose for a modular gulp compiler you can check one of my repositories like help-mediaqueries and ckd-css

**Comment by equinusocio** [comment]
PS: This is the best solution i found. I use a gulp task based on `gulp-inject` that inject the compiled css inside the html `*-style`template. This is the best method because if you inject the code directly inside the component template you will have issues with the editor (as you mentioned)

**Comment by superjose** [comment]
Thanks!!! I'll be checking into that. Been busy as of late!!!
